
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2019-2020 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.4.137")]
[assembly: AssemblyFileVersion("0.4.137")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("Topten.RichTextKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2020, 12, 14, 2, 37, 24, DateTimeKind.Utc);
}
	